// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1NKy6zd1odbonJhVU0UAQWIkXL-8EmU',
    appId: '1:265938293480:android:9cb7003206051170596f5d',
    messagingSenderId: '265938293480',
    projectId: 'chatapp-c495a',
    storageBucket: 'chatapp-c495a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1NKy6zd1odbonJhVU0UAQWIkXL-8EmU',
    appId: '1:265938293480:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '265938293480',
    projectId: 'chatapp-c495a',
    storageBucket: 'chatapp-c495a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1NKy6zd1odbonJhVU0UAQWIkXL-8EmU',
    appId: '1:265938293480:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '265938293480',
    projectId: 'chatapp-c495a',
    storageBucket: 'chatapp-c495a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1NKy6zd1odbonJhVU0UAQWIkXL-8EmU',
    appId: '1:265938293480:web:5e8c1f5d4b6a3c9e7f2a1b',
    messagingSenderId: '265938293480',
    projectId: 'chatapp-c495a',
    authDomain: 'chatapp-c495a.firebaseapp.com',
    storageBucket: 'chatapp-c495a.firebasestorage.app',
  );
}